baseURL = "https://joepeskett.github.io/"
languageCode = "en-us"
title = "Joe Peskett"
theme = "hugo-theme-cleanwhite"
staticDir = ["static"]
preserveTaxonomyNames = true
paginate = 5

[params]
  header_image = "img/header.jpg"
  description = "My personal blog"
  keyword = ""
  slogan = "Blog - Work In Progress. "

  title_404 = "AHHHHHHHHH!!!!!!"

  omit_categories = false


  about_me = true
  sidebar_about_description = "Machine Learning & Software engineer."
  sidebar_avatar = "img/face.jpg"
  featured_tags = true
  featured_condition_size = 0
  #
  #
  #
  [params.social]
  email = "jwpeskett@gmail.com"
  linkedin = "https://linkin.com/in/joe-peskett"
  github = "https://github.com/joepeskett"
  website = "https://joepeskett.myportfolio.com"

  [[params.additional_menus]]
  title = "ABOUT"
  href = "/top/about"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
    stype = "dracula"
